# Generated by Django 3.2.8 on 2021-10-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='media/fooditems/%Y/%m')),
                ('category', models.CharField(choices=[('chicken', 'chicken'), ('drinks', 'drinks'), ('steak', 'steak'), ('pizzas', 'pizzas'), ('burgers', 'burgers'), ('sandwich', 'sandwich'), ('nuggets', 'nuggets'), ('other', 'other')], max_length=200)),
                ('description', models.TextField()),
                ('is_veg', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('limit', models.IntegerField(default=2)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
