# Generated by Django 3.2.8 on 2021-10-31 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('details_message', models.TextField()),
            ],
        ),
    ]
